// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201103073245_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("API.Entities.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 11, 8, 21, 32, 44, 954, DateTimeKind.Local).AddTicks(6120),
                            Description = "Server",
                            IsDone = false
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 11, 9, 1, 32, 44, 957, DateTimeKind.Local).AddTicks(7924),
                            Description = "API",
                            IsDone = false
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 11, 8, 20, 32, 44, 957, DateTimeKind.Local).AddTicks(8285),
                            Description = "Client",
                            IsDone = false
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2020, 11, 8, 14, 32, 44, 957, DateTimeKind.Local).AddTicks(8306),
                            Description = "Front",
                            IsDone = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
